Traceback (most recent call last):
  File "/fs02/rl54/Abi/platelet-analysis/massive/M3_cluster_platelets_1.py", line 59, in <module>
    df = umap_dbscan_cluster(df, 'SCnV_mv', save=sp, eps_list=eps_list, cols=cols)
  File "/fs02/rl54/Abi/platelet-analysis/src/plateletanalysis/analysis/clustering.py", line 74, in umap_dbscan_cluster
    df, data, idxs = umap_embedding(df, emb_name, save, cols, umap_cols)
  File "/fs02/rl54/Abi/platelet-analysis/src/plateletanalysis/analysis/clustering.py", line 168, in umap_embedding
    sml_df = RobustScaler().fit_transform(sml_df)
  File "/projects/rl54/Abi/miniconda/envs/platelets/lib/python3.8/site-packages/sklearn/base.py", line 852, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/projects/rl54/Abi/miniconda/envs/platelets/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 1488, in fit
    X = self._validate_data(
  File "/projects/rl54/Abi/miniconda/envs/platelets/lib/python3.8/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/projects/rl54/Abi/miniconda/envs/platelets/lib/python3.8/site-packages/sklearn/utils/validation.py", line 805, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 25)) while a minimum of 1 is required by RobustScaler.
